name: PRCleanup

on:
  pull_request:
    types: [closed]

env:
  # github.repository.name as <account>
  ACCOUNT: '${{ github.event.repository.name }}'
  PR_NUMBER: '${{ github.event.pull_request.number }}'
  PACKAGE_TYPE: 'container'

jobs:
  pr-cleanup:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      -
        name: 'Install Helm'
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      -
        name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      -
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST_AV2 }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      -
        name: Remove PR Environment Helm Release
        env:
          TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
          TRAINING_NAMESPACE: 'pitc-cicd-dagger-techlab-test'
          TRAINING_VERSION: '${{ github.sha }}'
        run: |
          helm uninstall $TRAINING_HELM_RELEASE --ignore-not-found --kubeconfig $HOME/.kube/config  --namespace=$TRAINING_NAMESPACE
      -
        name: Delete Tags on Image Registry
        id: delete_tags
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/ORG/packages/${PACKAGE_TYPE}/${ACCOUNT}/versions/pr-${PR_NUMBER}
