name: PRCleanup
on:
  pull_request:
    types: [closed]

jobs:
  pr-cleanup:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      -
        name: 'Install Helm'
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      -
        name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      -
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST_AV2 }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      -
        name: Remove PR Environment Helm Release
        env:
          TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
          TRAINING_NAMESPACE: 'pitc-cicd-dagger-techlab-test'
          TRAINING_VERSION: '${{ github.sha }}'
        run: |
          helm uninstall $TRAINING_HELM_RELEASE --ignore-not-found --kubeconfig $HOME/.kube/config  --namespace=$TRAINING_NAMESPACE
      -
        name: Delete Tags on Image Registry
        id: delete_tags
        env:
          PR_NUMBER: '${{ github.event.pull_request.number }}'
          REGISTRY_API_AUTH: '${{ secrets.REGISTRY_USERNAME }}:${{ secrets.REGISTRY_AUTH }}'
          PROJECT: 'pitc-techlabs-public'
          REPOSITORY: 'dagger-techlab'
        run: |
          curl -X DELETE \
            -u ${REGISTRY_API_AUTH} \
            https://harbor.puzzle.ch/api/v2.0/projects/${PROJECT}/repositories/${REPOSITORY}/artifacts/pr-${PR_NUMBER}
